const AUTH = {
  LOGIN: '/api/auth/login',
  REGISTER: '/api/auth/register',
  ME: '/api/auth/me',
  LOGOUT: '/api/auth/logout',
  ROLES: '/api/auth/roles'
} as const;

export const API_ROUTES = {
  ...AUTH,

  SUPPLIERS: '/api/procurement/suppliers',
  SUPPLIER: (id: string) => `/api/procurement/suppliers/${id}`,
  SUPPLIERS_META: '/api/procurement/suppliers/meta',
  SUPPLIER_PURCHASE_HISTORY: (id: string) => `/api/procurement/suppliers/${id}/purchase-history`,
  REQUISITIONS: '/api/procurement/requisitions',
  REQUISITION: (id: string) => `/api/procurement/requisitions/${id}`,
  PURCHASE_ORDERS: '/api/procurement/purchase-orders',
  PURCHASE_ORDER: (id: string) => `/api/procurement/purchase-orders/${id}`,
  GRNS: '/api/procurement/grns',
  GRN: (id: string) => `/api/procurement/grns/${id}`,

  ITEMS: '/api/inventory/items',
  ITEM: (id: string) => `/api/inventory/items/${id}`,
  WAREHOUSES: '/api/inventory/warehouses',
  STOCK_BALANCES: '/api/inventory/stock-balances',
  STOCK_MOVEMENTS: '/api/inventory/stock-movements',
  TRANSFERS: '/api/inventory/transfers',
  TRANSFER: (id: string) => `/api/inventory/transfers/${id}`,
  LOW_STOCK: '/api/inventory/low-stock',
  EXPIRING: '/api/inventory/expiring',

  RECIPES: '/api/production/recipes',
  RECIPE: (id: string) => `/api/production/recipes/${id}`,
  BATCHES: '/api/production/batches',
  BATCH: (id: string) => `/api/production/batches/${id}`,
  BATCH_REQUEST_MATERIALS: (id: string) => `/api/production/batches/${id}/request-materials`,
  BATCH_APPROVE_MATERIALS: (id: string) => `/api/production/batches/${id}/approve-materials`,
  BATCH_RESERVE: (id: string) => `/api/production/batches/${id}/reserve-materials`,
  BATCH_START: (id: string) => `/api/production/batches/${id}/start`,
  BATCH_SUBMIT_QUALITY: (id: string) => `/api/production/batches/${id}/submit-quality`,
  BATCH_QUALITY: (id: string) => `/api/production/batches/${id}/quality-result`,
  BATCH_CLOSE: (id: string) => `/api/production/batches/${id}/close`,
  BATCH_CANCEL: (id: string) => `/api/production/batches/${id}/cancel`,
  BATCH_ASSIGN_WORKERS: (id: string) => `/api/production/batches/${id}/assign-workers`,
  MATERIAL_REQUESTS: '/api/production/material-requests',
  MATERIAL_REQUEST: (id: string) => `/api/production/material-requests/${id}`,
  MATERIAL_REQUEST_APPROVE: (id: string) => `/api/production/material-requests/${id}/approve`,
  MATERIAL_REQUEST_ISSUE: (id: string) => `/api/production/material-requests/${id}/issue`,
  QUALITY_CHECKS: '/api/production/quality-checks',
  WASTAGE: '/api/production/wastage',
  SHIFT_REPORTS: '/api/production/shift-reports',
  PRODUCTION_DASHBOARD: '/api/production/dashboard',

  BRANCHES: '/api/branches',
  BRANCH: (id: string) => `/api/branches/${id}`,
  BRANCH_DASHBOARD: (id: string) => `/api/branches/${id}/dashboard`,
  BRANCH_SALES: (branchId: string) => `/api/branch-operations/${branchId}/sales`,
  BRANCH_SALE: (branchId: string, id: string) => `/api/branch-operations/${branchId}/sales/${id}`,
  BRANCH_EXPENSES: (branchId: string) => `/api/branch-operations/${branchId}/expenses`,
  BRANCH_SHIFT_CLOSES: (branchId: string) => `/api/branch-operations/${branchId}/shift-closes`,
  BRANCH_SHIFT_CLOSE: (branchId: string, id: string) => `/api/branch-operations/${branchId}/shift-closes/${id}`,
  BRANCH_SHIFT_CLOSE_SUBMIT: (branchId: string, id: string) =>
    `/api/branch-operations/${branchId}/shift-closes/${id}/submit`,
  BRANCH_SHIFT_CLOSE_APPROVE: (branchId: string, id: string) =>
    `/api/branch-operations/${branchId}/shift-closes/${id}/approve`,
  BRANCH_SHIFT_CLOSE_REJECT: (branchId: string, id: string) =>
    `/api/branch-operations/${branchId}/shift-closes/${id}/reject`,

  CUSTOMERS: '/api/sales/customers',
  CUSTOMER: (id: string) => `/api/sales/customers/${id}`,
  QUOTATIONS: '/api/sales/quotations',
  QUOTATION: (id: string) => `/api/sales/quotations/${id}`,
  QUOTATION_CONVERT: (id: string) => `/api/sales/quotations/${id}/convert-to-order`,
  SALES_ORDERS: '/api/sales/orders',
  SALES_ORDER: (id: string) => `/api/sales/orders/${id}`,
  SALES_ORDER_CONFIRM: (id: string) => `/api/sales/orders/${id}/confirm`,
  SALES_ORDER_CANCEL: (id: string) => `/api/sales/orders/${id}/cancel`,
  DELIVERY_NOTES: '/api/sales/delivery-notes',
  DELIVERY_NOTE: (id: string) => `/api/sales/delivery-notes/${id}`,
  INVOICES: '/api/sales/invoices',
  INVOICE: (id: string) => `/api/sales/invoices/${id}`,
  INVOICE_PAYMENT: (id: string) => `/api/sales/invoices/${id}/payment`,
  INVOICE_PDF: (id: string) => `/api/sales/invoices/${id}/pdf`,
  PAYMENTS: '/api/sales/payments',

  ACCOUNTS: '/api/finance/accounts',
  ACCOUNT: (id: string) => `/api/finance/accounts/${id}`,
  BANK_ACCOUNTS: '/api/finance/bank-accounts',
  JOURNALS: '/api/finance/journals',
  JOURNAL: (id: string) => `/api/finance/journals/${id}`,
  JOURNAL_POST: (id: string) => `/api/finance/journals/${id}/post`,
  PETTY_CASH_REQUESTS: '/api/finance/petty-cash',
  PETTY_CASH_APPROVE: (id: string) => `/api/finance/petty-cash/${id}/approve`,
  BUDGETS: '/api/finance/budgets',
  BUDGET: (id: string) => `/api/finance/budgets/${id}`,
  FIXED_ASSETS: '/api/finance/fixed-assets',

  EMPLOYEES: '/api/hr/employees',
  EMPLOYEE: (id: string) => `/api/hr/employees/${id}`,
  ATTENDANCE: '/api/hr/attendance',
  LEAVE_REQUESTS: '/api/hr/leave',
  LEAVE_REQUEST: (id: string) => `/api/hr/leave/${id}`,
  LEAVE_APPROVE: (id: string) => `/api/hr/leave/${id}/approve`,
  LEAVE_REJECT: (id: string) => `/api/hr/leave/${id}/reject`,
  PAYROLL: '/api/hr/payroll',
  PAYROLL_RECORD: (id: string) => `/api/hr/payroll/${id}`,
  PAYROLL_APPROVE: (id: string) => `/api/hr/payroll/${id}/approve`,

  MACHINES: '/api/maintenance/machines',
  MACHINE: (id: string) => `/api/maintenance/machines/${id}`,
  MAINTENANCE_SCHEDULES: '/api/maintenance/schedules',
  MAINTENANCE_SCHEDULE: (id: string) => `/api/maintenance/schedules/${id}`,
  MAINTENANCE_COMPLETE: (id: string) => `/api/maintenance/schedules/${id}/complete`,
  BREAKDOWNS: '/api/maintenance/breakdowns',
  BREAKDOWN: (id: string) => `/api/maintenance/breakdowns/${id}`,
  BREAKDOWN_RESOLVE: (id: string) => `/api/maintenance/breakdowns/${id}/resolve`,

  SETTINGS_USERS: '/api/settings/users',
  SETTINGS_USER: (id: string) => `/api/settings/users/${id}`,
  SETTINGS_USER_ACTIVATE: (id: string) => `/api/settings/users/${id}/activate`,
  SETTINGS_USER_DEACTIVATE: (id: string) => `/api/settings/users/${id}/deactivate`,
  SETTINGS_ROLES: '/api/settings/roles',
  SETTINGS_ROLE: (id: string) => `/api/settings/roles/${id}`,
  SETTINGS_ROLE_PERMISSIONS: (id: string) => `/api/settings/roles/${id}/permissions`,
  SETTINGS_PERMISSIONS: '/api/settings/permissions',
  AUDIT_LOGS: '/api/settings/audit-logs',
  NUMBER_SERIES: '/api/settings/number-series',

  REPORTS: '/api/reports',

  NOTIFICATIONS: '/api/notifications',
  NOTIFICATION_READ: (id: string) => `/api/notifications/${id}/read`,
  NOTIFICATIONS_READ_ALL: '/api/notifications/read-all',
  NOTIFICATIONS_UNREAD_COUNT: '/api/notifications/unread-count',

  AUTH,
  PROCUREMENT: {
    SUPPLIERS: '/api/procurement/suppliers',
    SUPPLIER: (id: string) => `/api/procurement/suppliers/${id}`,
    REQUISITIONS: '/api/procurement/requisitions',
    REQUISITION: (id: string) => `/api/procurement/requisitions/${id}`,
    PURCHASE_ORDERS: '/api/procurement/purchase-orders',
    PURCHASE_ORDER: (id: string) => `/api/procurement/purchase-orders/${id}`,
    GRNS: '/api/procurement/grns',
    GRN: (id: string) => `/api/procurement/grns/${id}`,
    META: '/api/procurement/meta'
  },
  INVENTORY: {
    ITEMS: '/api/inventory/items',
    WAREHOUSES: '/api/inventory/warehouses',
    STOCK_BALANCES: '/api/inventory/stock-balances',
    STOCK_MOVEMENTS: '/api/inventory/stock-movements',
    TRANSFERS: '/api/inventory/transfers',
    LOW_STOCK: '/api/inventory/low-stock',
    EXPIRING: '/api/inventory/expiring',
    META: '/api/inventory/meta'
  },
  PRODUCTION: {
    DASHBOARD: '/api/production/dashboard',
    RECIPES: '/api/production/recipes',
    RECIPE: (id: string) => `/api/production/recipes/${id}`,
    BATCHES: '/api/production/batches',
    BATCH: (id: string) => `/api/production/batches/${id}`,
    BATCH_REQUEST_MATERIALS: (id: string) => `/api/production/batches/${id}/request-materials`,
    BATCH_APPROVE_MATERIALS: (id: string) => `/api/production/batches/${id}/approve-materials`,
    BATCH_RESERVE: (id: string) => `/api/production/batches/${id}/reserve-materials`,
    BATCH_START: (id: string) => `/api/production/batches/${id}/start`,
    BATCH_SUBMIT_QUALITY: (id: string) => `/api/production/batches/${id}/submit-quality`,
    BATCH_QUALITY: (id: string) => `/api/production/batches/${id}/quality-result`,
    BATCH_CLOSE: (id: string) => `/api/production/batches/${id}/close`,
    BATCH_CANCEL: (id: string) => `/api/production/batches/${id}/cancel`,
    BATCH_ASSIGN_WORKERS: (id: string) => `/api/production/batches/${id}/assign-workers`,
    MATERIAL_REQUESTS: '/api/production/material-requests',
    MATERIAL_REQUEST: (id: string) => `/api/production/material-requests/${id}`,
    MATERIAL_REQUEST_APPROVE: (id: string) => `/api/production/material-requests/${id}/approve`,
    MATERIAL_REQUEST_ISSUE: (id: string) => `/api/production/material-requests/${id}/issue`
  },
  BRANCH_OPERATIONS: {
    SALES: (branchId: string) => `/api/branch-operations/${branchId}/sales`,
    EXPENSES: (branchId: string) => `/api/branch-operations/${branchId}/expenses`,
    SHIFT_CLOSES: (branchId: string) => `/api/branch-operations/${branchId}/shift-closes`,
    SHIFT_CLOSE_DETAIL: (branchId: string, shiftCloseId: string) =>
      `/api/branch-operations/${branchId}/shift-closes/${shiftCloseId}`
  },
  BRANCHES_COMPAT: {
    LIST: '/api/branches',
    DETAIL: (id: string) => `/api/branches/${id}`,
    DASHBOARD: (id: string) => `/api/branches/${id}/dashboard`,
    STOCK: (id: string) => `/api/branches/${id}/stock`
  },
  SALES: {
    CUSTOMERS: '/api/sales/customers',
    CUSTOMER: (id: string) => `/api/sales/customers/${id}`,
    QUOTATIONS: '/api/sales/quotations',
    QUOTATION: (id: string) => `/api/sales/quotations/${id}`,
    SALES_ORDERS: '/api/sales/orders',
    SALES_ORDER: (id: string) => `/api/sales/orders/${id}`,
    SALES_ORDER_CONFIRM: (id: string) => `/api/sales/orders/${id}/confirm`,
    INVOICES: '/api/sales/invoices',
    INVOICE: (id: string) => `/api/sales/invoices/${id}`,
    INVOICE_PAYMENT: (id: string) => `/api/sales/invoices/${id}/payment`
  },
  FINANCE: {
    DASHBOARD: '/api/finance/dashboard',
    JOURNAL_ENTRIES: '/api/finance/journal-entries',
    JOURNAL_ENTRY: (id: string) => `/api/finance/journal-entries/${id}`,
    JOURNAL_POST: (id: string) => `/api/finance/journal-entries/${id}/post`
  },
  NOTIFICATIONS_COMPAT: {
    LIST: '/api/notifications',
    MARK_READ: (id: string) => `/api/notifications/${id}/read`,
    READ_ALL: '/api/notifications/read-all',
    UNREAD_COUNT: '/api/notifications/unread-count',
    MARK_ALL_READ: '/api/notifications/read-all'
  },
  REPORTS_COMPAT: {
    LIST: '/api/reports',
    DASHBOARD: '/api/reports/dashboard',
    EXPORT_CSV: '/api/reports/export/csv',
    EXPORT_PDF: '/api/reports/export/pdf'
  },
  SETTINGS: {
    USERS: '/api/settings/users',
    ROLES: '/api/settings/roles',
    PERMISSIONS: '/api/settings/permissions',
    AUDIT_LOGS: '/api/settings/audit-logs',
    OVERVIEW: '/api/settings/overview',
    SUMMARY: '/api/settings/summary'
  },
  SUPPLIERS_COMPAT: {
    LIST: '/api/procurement/suppliers',
    DETAIL: (id: string) => `/api/procurement/suppliers/${id}`,
    META: '/api/procurement/suppliers/meta',
    PURCHASE_HISTORY: (id: string) => `/api/procurement/suppliers/${id}/purchase-history`
  }
} as const;
